// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAackH_Wmv3B7gQgx8UC4ZxJSwNHWAw_pU',
    appId: '1:1077893614286:android:fd320850eb02bdc60c9e9f',
    messagingSenderId: '1077893614286',
    projectId: 'doctory-1aca1',
    storageBucket: 'doctory-1aca1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAWQjAH5Wee2Y0ZvN1ezOGcs8P4OiTwHg',
    appId: '1:1077893614286:ios:17e5fece5a5a61b10c9e9f',
    messagingSenderId: '1077893614286',
    projectId: 'doctory-1aca1',
    storageBucket: 'doctory-1aca1.firebasestorage.app',
    androidClientId: '1077893614286-blko3bppf5iskolvbbg4ttiku2t9363j.apps.googleusercontent.com',
    iosClientId: '1077893614286-upsfe0te88flm0gc3hl2af0qjdfnk6le.apps.googleusercontent.com',
    iosBundleId: 'com.clinichub.doctory',
  );
}
