name: Flutter CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta' or 'master'

      - name: Set Flutter version for CI
        run: |
          VERSION=$(grep "version: " pubspec.yaml | awk '{print $2}')
          OLD_BUILD_NUMBER=$(echo $VERSION | cut -d '+' -f 2)
          NEW_BUILD_NUMBER=${{ github.run_number }} # Use GitHub's run number as the build number
          
          # If there's no build number, use 1 or GITHUB_RUN_NUMBER directly
          if [ -z "$OLD_BUILD_NUMBER" ]; then
            NEW_VERSION=$(echo $VERSION | cut -d '+' -f 1)+$NEW_BUILD_NUMBER
          else
            NEW_VERSION=$(echo $VERSION | cut -d '+' -f 1)+$NEW_BUILD_NUMBER
          fi

          echo "Original version: $VERSION"
          echo "New version: $NEW_VERSION"
          sed -i "s/version: $VERSION/version: $NEW_VERSION/" pubspec.yaml
        working-directory: ./

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase App Distribution
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:1077893614286:android:51c43c18b7b298330c9e9f --token ${{ secrets.FIREBASE_CLI_TOKEN }} --release-notes "Build from GitHub Actions"

