name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or 'beta' or 'master'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: |
          BUILD_NAME_FLAG=""
          if [ ! -z "${{ github.run_number }}" ]; then
            BUILD_NAME_FLAG="--build-name=${{ github.run_number }}"
          fi

          flutter build apk -t lib/main_dev.dart --release $BUILD_NAME_FLAG --build-number=${{ github.run_number }}


      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: 1:214655616174:android:441c747086cfe9fb35993f
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          file: build/app/outputs/flutter-apk/app-release.apk
          releaseNotes: "Build from GitHub Actions"


